### ISSUE TITLE
the app keeps timing out

### ISSUE THREAD

**Issue by brunj7** [daattali/shiny-server#10]
Hi, 

I landed on your Shiny app following an URL from the R Shiny documentation and noticed that the app is displaying a time-out message after a few seconds.

Best,
Julien

**Comment by daattali** [comment]
Hi, thanks for reporting! Which app was this?

**Comment by daattali** [comment]
I believe you were talking about https://daattali.com/shiny/persistent-data-storage/ - it's fixed. Thanks!

**Comment by brunj7** [comment]
Yes, that was this one. My apologies for not specifying it and thank you for the quick fix!
