### ISSUE TITLE
persistent storage app not working

### ISSUE THREAD

**Issue by mcolvin** [daattali/shiny-server#6]
Nice tutorial on persistent data storage in Shiny.  I have been trying to get some a dropbox storage to go, with no luck.  I checked your app https://daattali.com/shiny/persistent-data-storage/ and they don't seem to run either for any of the remote storage options. Leads me to think there is a larger authentication issue or that your demo apps for remote storage are purposely disabled which in this case is a non-issue. Any Ideas?   

Below is a screen shot with the error from your demo app
![image](https://cloud.githubusercontent.com/assets/654215/23713928/1a4a4446-03ed-11e7-856a-d67c9225f1bf.png)

**Comment by daattali** [comment]
It's the dropbox and google sheets specifically that don't work, the rest of the storage types (remote as well) do work. But you're right, it is because of an underlying issue with expired authentication keys. I'll try to take a look when I can

**Comment by daattali** [comment]
They all work now :+1:
