### ISSUE TITLE
dateInput parsed into multiple columns in table

### ISSUE THREAD

**Issue by ptcougopinto** [daattali/shiny-server#8]
Hi,

Excellent and much needed implementation.

I found an issue with date and time inputs when using local tables as storage system: their posix elements are spread across multiple columns. Small example below.

library(shiny)

outputDir <- "RESPONSES"

fields <- c("Date", "Time")

saveData <- function(data) {
  data <- t(data)
  fileName <- sprintf("%s_%s.csv", as.integer(Sys.time()), digest::digest(data))
  write.csv(
    x = data,
    file = file.path(outputDir, fileName), 
    row.names = FALSE, quote = TRUE
  )
}

loadData <- function() {
  files <- list.files(outputDir, full.names = TRUE)
  data <- lapply(files, read.csv, stringsAsFactors = FALSE) 
  data <- do.call(rbind, data)
  data
}

ui <- fluidPage(
  dateInput("Date", "Date",
  format = "ddmmyyyy",
  value = ""),
  timeInput("Time", "Time",
  seconds = F),
  actionButton("Submit", "Submit", width = "280px"),
  hr(),
  DT::dataTableOutput("responses", width = 300), tags$hr()
)

server = function(input, output, session) {
  formData <- reactive({
    data <- sapply(fields, function(x) input[[x]])
    data
  })
  
  observeEvent(input$Submeter, {
    saveData(formData())
  })
  output$responses <- DT::renderDataTable({
    input$Submeter
    loadData()
  })     
}

shinyApp(ui, server)

**Comment by daattali** [comment]
Thanks for the report!

I can't run that code - what's a timeInput?

Also, please try to format your code so it's a bit more readable in the future

**Comment by daattali** [comment]
Even after removing the timeInput, the code doesn't work. Please make sure the code you submit correctly shows the problem

**Comment by ptcougopinto** [comment]
intputTime comes from a specific package, inputTime. Following code should work. Also, the output in the CSV file coming from dateInput is not corresponding to the actual date inserted (Apr 13 1949 instead of Apr 15 2019).

(Newbie to GitHub, sorry about the code format)

`library(shiny)
library(shinyTime)

outputDir <- "RESPONSES"

fields <- c("Date","Time")

saveData <- function(data) {
  data <- t(data)
  fileName <- sprintf("%s_%s.csv", as.integer(Sys.time()), digest::digest(data))
  write.csv(
    x = data,
    file = file.path(outputDir, fileName),
    row.names = FALSE, quote = TRUE
  )
}

loadData <- function() {
  files <- list.files(outputDir, full.names = TRUE)
  data <- lapply(files, read.csv, stringsAsFactors = FALSE)
  data <- do.call(rbind, data)
  data
}

ui <- fluidPage(
  dateInput("Date", "Date",
            format = "ddmmyyyy",
            value = ""),
  timeInput("Time", "Time",
            seconds = F),
  actionButton("Submit", "Submit", width = "280px")
)

server = function(input, output, session) {
  formData <- reactive({
    data <- sapply(fields, function(x) input[[x]])
    data
  })
  
  observeEvent(input$Submit, {
    saveData(formData())
  })
}

shinyApp(ui, server)
`

**Comment by daattali** [comment]
If this code works, then can you highlight the exact places where there is currently a problem and what the fix is? Are you familiar with GitHub Pull Requests - a way for you to directly make changes my project? I would welcome a pull request, that way I can see exactly what needed to change and you'll officially go on record as a contributor!
