### ISSUE TITLE
Error- Do not know how to convert 'data$timestamp' to class “POSIXct"

### ISSUE THREAD

**Issue by smitpate08** [daattali/shiny-server#9]
Hi,

Great tutorial! I tried running the code file but unfortunately I got below error in Shiny Server.  This error was received for this [code](https://github.com/daattali/shiny-server/blob/master/mimic-google-form/app.R) for this [article](https://deanattali.com/2015/06/14/mimicking-google-form-shiny/)

`Error :do not know how to convert 'data$timestamp' to class “POSIXct"`
**SnapShot of the error:**
![image](https://user-images.githubusercontent.com/29586703/60475644-5e955700-9c46-11e9-9738-643d9bf0c8db.png)

Any help is appreciated!

**Comment by daattali** [comment]
Sorry, this repo is not a place to get shiny help. I suggest asking on an online shiny forum such as RStudio Community https://community.rstudio.com/c/shiny or StackOverflow
